version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - "80:80"

  react-front:
    build:
      dockerfile: dev.Dockerfile
      context: ./ReactFront
    env_file:
      - ./ReactFront/.env
    volumes:
      - /usr/app/node_modules
      - ./ReactFront:/usr/app
    command: ["npm", "run", "start"]

  node-back:
    build:
      context: ./NodeBack
      dockerfile: dev.Dockerfile
    env_file:
      - ./NodeBack/.env
    volumes:
      - /usr/app/node_modules
      - ./NodeBack:/usr/app
    command: ["npm", "run", "dev"]
